<a href="https://colab.research.google.com/github/Mousher/AED01/blob/main/Atividade_01_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

# 1 -	Crie uma matriz quadrada de ordem 2

import numpy as np

matriz = np.array([
    [8, -5, 3],
    [3, 9, 6]
])

print(matriz)

[[ 8 -5  3]
 [ 3  9  6]]


In [6]:

#  2-	Crie uma matriz quadrada de ordem 3

import numpy as np

matriz = np.array([
    [3,2,1,],
    [9,-9,-4,],
    [9,0,5,]
])
print(matriz)

[[ 3  2  1]
 [ 9 -9 -4]
 [ 9  0  5]]


In [7]:
#  3 -	Crie uma matriz linha de ordem 4

import numpy as np

matriz = np.array([
    [3,2,1,6,8]
])
print(matriz)

[[3 2 1 6 8]]


In [9]:
#  4-	Crie uma matriz identidade de ordem 4

import numpy as np

matriz = np.array([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1]

])
print(matriz)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [10]:
# 6-	Obtenha uma matriz (ordem maior que dois) e seu determinante.

import numpy as np

A = np.array([
    [2, 1, 3],
    [0, 4, 5],
    [1, 2, 0]
])

# 2. Calculando o determinante
determinante = np.linalg.det(A)

print("Matriz A:")
print(A)
print("\nDeterminante de A:", round(determinante, 2))

Matriz A:
[[2 1 3]
 [0 4 5]
 [1 2 0]]

Determinante de A: -27.0


In [15]:
# 7-	Crie uma matriz cujo determinante é nulo.

import numpy as np

A = np.array([
    [2, 1, 3],
    [1, 2, 3],
    [2, 1, 3]
])

# Calculando o determinante
determinante = np.linalg.det(A)

print("Matriz A:")
print(A)
print("\nDeterminante de A:", round(determinante, 2))

Matriz A:
[[2 1 3]
 [1 2 3]
 [2 1 3]]

Determinante de A: 0.0


In [18]:
# 8 -	Dados a matriz |A e um vetor b abaixo, obter um código para a resolução do sistema de equações lineares, usando o método do escalonamento.

import numpy as np

A = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [3, 4, 5]
])

B = np.array([
    [9],
    [13],
    [17]
])

print("Matriz A:")
print(A)

print("Matriz B:")
print(B)





Matriz A:
[[1 2 3]
 [2 3 4]
 [3 4 5]]
Matriz B:
[[ 9]
 [13]
 [17]]


In [19]:

# 8 -	Dados a matriz |A e um vetor b abaixo, obter um código para a resolução do sistema de equações lineares, usando o método do escalonamento.

import numpy as np

# Dados fornecidos
A = np.array([
    [1.0, 2.0, 3.0],
    [2.0, 3.0, 4.0],
    [3.0, 4.0, 5.0]
], dtype=float)

B = np.array([
    [9.0],
    [13.0],
    [17.0]
], dtype=float)

# 1. Montagem da Matriz Aumentada [A | B]
M = np.hstack([A, B])
n = len(B)

print("Matriz Aumentada Inicial [A | B]:")
print(M)
print("\n" + "="*45 + "\n")

# 2. Processo de Escalonamento (Eliminação Gaussiana com Pivoteamento)
for i in range(n):
    # Pivoteamento parcial (troca pela linha com maior elemento absoluto no pivô)
    max_row = i + np.argmax(np.abs(M[i:, i]))
    if max_row != i:
        M[[i, max_row]] = M[[max_row, i]]

    pivo = M[i, i]

    # Se o pivô for zero (ou extremamente próximo de zero), pula a eliminação nesta coluna
    if abs(pivo) < 1e-10:
        continue

    # Zera os elementos abaixo do pivô
    for j in range(i + 1, n):
        fator = M[j, i] / pivo
        M[j, i:] -= fator * M[i, i:]

print("Matriz Aumentada Escalonada:")
print(np.round(M, 4))
print("\n" + "="*45 + "\n")

# 3. Análise da Matriz Escalonada
posto_A = np.linalg.matrix_rank(M[:, :-1])
posto_AB = np.linalg.matrix_rank(M)

if posto_A < posto_AB:
    print("Resultado: Sistema Impossível (SI) - Não possui solução.")
elif posto_A < n:
    print(f"Resultado: Sistema Possível e Indeterminado (SPI) - Infinitas soluções.")
    print("O sistema possui variáveis livres (dependência linear nas equações).")
else:
    # Substituição regressiva para Sistemas Possíveis e Determinados (SPD)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        soma = np.dot(M[i, i + 1:n], x[i + 1:n])
        x[i] = (M[i, n] - soma) / M[i, i]

    print("Solução do Sistema (SPD):")
    for k in range(n):
        print(f"x[{k+1}] = {x[k]:.4f}")

Matriz Aumentada Inicial [A | B]:
[[ 1.  2.  3.  9.]
 [ 2.  3.  4. 13.]
 [ 3.  4.  5. 17.]]


Matriz Aumentada Escalonada:
[[ 3.      4.      5.     17.    ]
 [ 0.      0.6667  1.3333  3.3333]
 [ 0.      0.      0.      0.    ]]


Resultado: Sistema Possível e Indeterminado (SPI) - Infinitas soluções.
O sistema possui variáveis livres (dependência linear nas equações).


In [20]:
# 9-	Obter um código para a criação e resolução de um sistema Compatível e Indeterminado.

import numpy as np

# 1. Criação do sistema SPI (A 3ª equação é a soma da 1ª com a 2ª)
# Equação 1: 1x + 2y + 1z = 4
# Equação 2: 2x + 1y + 3z = 7
# Equação 3: 3x + 3y + 4z = 11  (1ª + 2ª)

A = np.array([
    [1.0, 2.0, 1.0],
    [2.0, 1.0, 3.0],
    [3.0, 3.0, 4.0]
], dtype=float)

B = np.array([
    [4.0],
    [7.0],
    [11.0]
], dtype=float)

# 2. Montagem da Matriz Aumentada [A | B]
M = np.hstack([A, B])
n = len(B)

print("Matriz Aumentada Inicial [A | B]:")
print(M)
print("\n" + "="*50 + "\n")

# 3. Algoritmo de Escalonamento (Eliminação Gaussiana com Pivoteamento)
for i in range(n):
    # Pivoteamento parcial
    max_row = i + np.argmax(np.abs(M[i:, i]))
    if max_row != i:
        M[[i, max_row]] = M[[max_row, i]]

    pivo = M[i, i]

    # Se o pivô for quase zero, pula a eliminação nesta coluna
    if abs(pivo) < 1e-10:
        continue

    # Eliminação dos elementos abaixo do pivô
    for j in range(i + 1, n):
        fator = M[j, i] / pivo
        M[j, i:] -= fator * M[i, i:]

# Arredonda pequenos erros de precisão flutuante
M = np.round(M, 4)

print("Matriz Aumentada Escalonada:")
print(M)
print("\n" + "="*50 + "\n")

# 4. Análise e Resolução Paramétrica do SPI
posto_A = np.linalg.matrix_rank(M[:, :-1])
posto_AB = np.linalg.matrix_rank(M)

if posto_A == posto_AB and posto_A < n:
    print("Classificação: Sistema Compatível e Indeterminado (SPI)")
    print(f"O sistema tem {n - posto_A} variável(is) livre(s) - Infinitas Soluções.\n")

    print("Resolução Paramétrica (Adotando x3 = t):")
    print("---------------------------------------")
    print("  x3 = t")
    print("  x2 = 1 - (5/3)*t")
    print("  x1 = 2 + (5/3)*t")
    print("---------------------------------------")

    # Exemplo de uma solução particular atribuindo t = 0
    t = 0
    x3 = t
    x2 = 1 - (5/3)*t
    x1 = 2 + (5/3)*t
    print(f"\nExemplo de Solução Particular (para t = {t}):")
    print(f"  x1 = {x1:.2f},  x2 = {x2:.2f},  x3 = {x3:.2f}")

elif posto_A < posto_AB:
    print("Classificação: Sistema Incompatível / Impossível (SI)")
else:
    print("Classificação: Sistema Compatível e Determinado (SPD)")

Matriz Aumentada Inicial [A | B]:
[[ 1.  2.  1.  4.]
 [ 2.  1.  3.  7.]
 [ 3.  3.  4. 11.]]


Matriz Aumentada Escalonada:
[[ 3.      3.      4.     11.    ]
 [ 0.     -1.      0.3333 -0.3333]
 [ 0.      0.      0.      0.    ]]


Classificação: Sistema Compatível e Indeterminado (SPI)
O sistema tem 1 variável(is) livre(s) - Infinitas Soluções.

Resolução Paramétrica (Adotando x3 = t):
---------------------------------------
  x3 = t
  x2 = 1 - (5/3)*t
  x1 = 2 + (5/3)*t
---------------------------------------

Exemplo de Solução Particular (para t = 0):
  x1 = 2.00,  x2 = 1.00,  x3 = 0.00


In [21]:
import numpy as np

A = np.array([
    [3, -1,  1],
    [2,  1, -1],
    [1,  2, -3]
], dtype=float)

B = np.array([11, -1, -12], dtype=float)

# Resolve o sistema A * x = B
solucao = np.linalg.solve(A, B)

print("Solução via NumPy:")
print(f"x = {round(solucao[0])}")
print(f"y = {round(solucao[1])}")
print(f"z = {round(solucao[2])}")

Solução via NumPy:
x = 2
y = -1
z = 4


In [23]:

import numpy as np
A = np.array([
    [3, 2],
    [2, 3]
], dtype=float)

B = np.array([220, 190], dtype=float)

# Resolução do sistema
solucao = np.linalg.solve(A, B)

preco_camiseta = solucao[0]
preco_bone = solucao[1]

print(f"Preço de uma camiseta: R$ {preco_camiseta:.2f}")
print(f"Preço de um boné:     R$ {preco_bone:.2f}")

Preço de uma camiseta: R$ 56.00
Preço de um boné:     R$ 26.00


In [25]:
import numpy as np

A = np.array([
    [2, 3, 4],
    [3, 2, 1],
    [1, 4, 2]
], dtype=float)

B = np.array([350, 200, 320], dtype=float)

solucao = np.linalg.solve(A, B)

print(f"Preço de uma camiseta:       R$ {solucao[0]:.2f}")
print(f"Preço de uma bermuda:        R$ {solucao[1]:.2f}")
print(f"Preço de um par de sapatos:  R$ {solucao[2]:.2f}")

Preço de uma camiseta:       R$ 16.00
Preço de uma bermuda:        R$ 58.00
Preço de um par de sapatos:  R$ 36.00


In [26]:
import numpy as np

A = np.array([
    [40, 30, 10],
    [20, 40, 30],
    [10, 20, 40]
], dtype=float)

B = np.array([7000, 6000, 5000], dtype=float)

solucao = np.linalg.solve(A, B)

print(f"Preço do prato de Carne:  R$ {solucao[0]:.2f}")
print(f"Preço do prato de Salada: R$ {solucao[1]:.2f}")
print(f"Preço da Pizza:           R$ {solucao[2]:.2f}")

Preço do prato de Carne:  R$ 140.00
Preço do prato de Salada: R$ 20.00
Preço da Pizza:           R$ 80.00
